<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>Norbix.Sdk.Types</RootNamespace>
    <AssemblyName>Norbix.Api.Types</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Generated/Hub.dtos.cs" />
    <Compile Remove="TaxonomyTreeEndpoints.cs" />
    <Compile Remove="INorbixRequest.cs" />
    <Compile Remove="ResponseStatus.cs" />
    <Compile Remove="NorbixRouteAttribute.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Norbix.Contracts\Norbix.Contracts.csproj" />
  </ItemGroup>

</Project>
