#!/usr/bin/env bash
# Refresh src/Norbix.Sdk.Types/Generated/Api.dtos.cs and Hub.dtos.cs from
# the gateway /metadata endpoints. Run from the repo root.
#
# Modes:
#   --local       Use local gateways on localhost:5002 / 5001 (default)
#   --prod        Use production gateways (api.norbix.dev / hub.norbix.dev)
#   --api-url U   Override API URL
#   --hub-url U   Override Hub URL
#
# What this script does:
#   1. Ensures the `x` dotnet tool is installed (per .config/dotnet-tools.json).
#   2. Runs `x csharp <metadata-url> <out>` for both gateways.
#   3. Strips ServiceStack imports and rewrites types so consumers never
#      see ServiceStack on the SDK's public surface.
#   4. Applies the regex fixes from /cloud/src/types/README.md.
#   5. Writes the cleaned output to the SDK's Generated folder.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TYPES_DIR="$ROOT/src/Norbix.Sdk.Types/Generated"
mkdir -p "$TYPES_DIR"

API_URL="http://localhost:5002"
HUB_URL="http://localhost:5001"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --local)   API_URL="http://localhost:5002"; HUB_URL="http://localhost:5001"; shift ;;
        --prod)    API_URL="https://api.norbix.dev"; HUB_URL="https://hub.norbix.dev"; shift ;;
        --api-url) API_URL="$2"; shift 2 ;;
        --hub-url) HUB_URL="$2"; shift 2 ;;
        *) echo "Unknown flag: $1" >&2; exit 2 ;;
    esac
done

echo "[sync-types] api-url: $API_URL"
echo "[sync-types] hub-url: $HUB_URL"

# 1. Ensure `x` is installed when possible. Some dev machines already have a
# global `x`, and the gateway also exposes /types/csharp directly, so a missing
# local tool should not block refreshes.
if ! command -v dotnet >/dev/null 2>&1; then
    echo "[sync-types] dotnet SDK is required (https://aka.ms/dotnet)" >&2
    exit 1
fi
( cd "$ROOT" && dotnet tool restore ) || echo "[sync-types] dotnet tool restore failed; will try global x or /types/csharp"

run_x() {
    local url="$1"
    local out="$2"
    local namespace="$3"
    local separator="?"
    if [[ "$url" == *"?"* ]]; then separator="&"; fi
    local typed_url="${url}${separator}GlobalNamespace=${namespace}"

    echo "[sync-types]   csharp $typed_url -> $out"

    if ( cd "$ROOT" && dotnet x csharp "$typed_url" "$out" ) >/dev/null 2>&1 && [[ -s "$out" ]]; then
        return
    fi

    if command -v x >/dev/null 2>&1 && x csharp "$typed_url" "$out" >/dev/null 2>&1 && [[ -s "$out" ]]; then
        return
    fi

    local direct_url="${url%/}/types/csharp${separator}GlobalNamespace=${namespace}"
    echo "[sync-types]   falling back to $direct_url"
    curl -fsSL "$direct_url" -o "$out"
}

# 2. Generate raw DTOs into a tempfile then clean.
TMP_API="$(mktemp -t norbix-api.XXXXXX.cs)"
TMP_HUB="$(mktemp -t norbix-hub.XXXXXX.cs)"
trap 'rm -f "$TMP_API" "$TMP_HUB"' EXIT

run_x "$API_URL" "$TMP_API" "Norbix.Sdk.Types.Api"
run_x "$HUB_URL" "$TMP_HUB" "Norbix.Sdk.Types.Hub"

# 3 + 4. Post-process: strip ServiceStack, swap to our types, fix README issues.
clean() {
    local input="$1"
    local output="$2"
    local namespace="$3"

    # Header
    {
        echo "// <auto-generated>"
        echo "//   Regenerated by scripts/sync-types.sh — do not edit by hand."
        echo "// </auto-generated>"
        echo ""
        echo "#nullable enable annotations"
        echo "#nullable disable warnings"
        echo ""
        echo "using System;"
        echo "using System.Collections.Generic;"
        echo "using System.Runtime.Serialization;"
        echo "using Norbix.Sdk.Types;"
        echo ""
        echo "namespace $namespace;"
        echo ""
    } > "$output"

    python3 - "$input" "$namespace" >> "$output" <<'PY'
import re
import sys

path, namespace = sys.argv[1], sys.argv[2]
src = open(path, encoding="utf-8").read()

src = re.sub(r"(?m)^using ServiceStack\b.*\n", "", src)
src = re.sub(r"(?m)^using ServiceStack\..*\n", "", src)
src = re.sub(r"(?m)^using System\b.*\n", "", src)
src = re.sub(r"(?m)^using System\..*\n", "", src)
src = re.sub(rf"(?m)^using {re.escape(namespace)};\s*\n", "", src)
src = re.sub(r"(?m)^\s*\[Api[^\]]*\]\s*\n", "", src)
src = re.sub(r"(?m)^\s*\[Ignore\]\s*\n", "", src)
src = re.sub(r"IReturn<([^>]+)>", r"INorbixRequest<\1>", src)
src = re.sub(r"\bIReturnVoid\b", "INorbixRequest", src)
src = re.sub(r"\[Route\(", "[NorbixRoute(", src)
src = re.sub(r"\bRoute\(", "NorbixRoute(", src)
src = re.sub(r"\bIPost\b|\bIGet\b|\bIHasSessionId\b|\bIHasBearerToken\b", "", src)
def clean_class_bases(match):
    name = match.group(1)
    bases = match.group(2)
    if not bases:
        return f"{name}\n    {{"
    kept = [
        part.strip()
        for part in bases.split(",")
        if part.strip() and (not part.strip().startswith("I") or part.strip().startswith("INorbixRequest"))
    ]
    return f"{name}\n        : {', '.join(kept)}\n    {{" if kept else f"{name}\n    {{"

src = re.sub(
    r"(public\s+partial\s+class\s+[A-Za-z0-9_]+(?:<[^>]+>)?)\s*(?::\s*([^{]+))?\s*\{",
    clean_class_bases,
    src,
    flags=re.MULTILINE,
)
src = re.sub(
    r"(public\s+partial\s+class\s+(?:MarketplaceIntegration|WebhookIntegration)\s*:\s*Integration\s*\{(?:(?!^\s*\}).)*?)public\s+virtual\s+string\s+Capability\s*\{\s*get;\s*set;\s*\}",
    r"\1public override string Capability { get; set; }",
    src,
    flags=re.MULTILINE | re.DOTALL,
)
src = re.sub(r"\bIList<JSchema>", "JSchema[]", src)
src = re.sub(r"\bIList<JToken>", "JToken[]", src)
src = re.sub(r"\bIList<string>", "string[]", src)
src = re.sub(r"\bDictionary<([^,<>\s]+)<([^<>]+)>>", r"Dictionary<\1, \2>", src)
src = re.sub(r"\b(NameValueCollection|FileInfo|Func<IDisposable>|Cookie|HttpStatusCode)\b", "object", src)
def ensure_schema_settings_id(match):
    block = match.group(0)
    if re.search(r"public\s+virtual\s+string\s+Id\s*\{\s*get;\s*set;\s*\}", block):
        return block
    return block.replace("{", "{\n\n        public virtual string Id { get; set; }", 1)

src = re.sub(
    r"public\s+partial\s+class\s+UpdateDatabaseSchemaSettingsRequest\s*\n\s*:\s*CodeMashRequestBase,\s*INorbixRequest<EmptyResponse>\s*\n\s*\{(?:(?!^\s*\}).)*?^\s*\}",
    ensure_schema_settings_id,
    src,
    count=1,
    flags=re.MULTILINE | re.DOTALL,
)

def ensure_delete_campaign_members(match):
    block = match.group(0)
    insert = []
    if not re.search(r"public\s+virtual\s+string\s+Id\s*\{\s*get;\s*set;\s*\}", block):
        insert.append("        public virtual string Id { get; set; }")
    if not re.search(r"public\s+virtual\s+string\s+DatabaseIntegrationId\s*\{\s*get;\s*set;\s*\}", block):
        insert.append("        public virtual string DatabaseIntegrationId { get; set; }")
    return block if not insert else block.replace("{", "{\n" + "\n".join(insert), 1)

src = re.sub(
    r"public\s+partial\s+class\s+DeleteEmailCampaignRequest\s*\n\s*:\s*CodeMashRequestBase,\s*INorbixRequest<EmptyResponse>\s*\n\s*\{(?:(?!^\s*\}).)*?^\s*\}",
    ensure_delete_campaign_members,
    src,
    count=1,
    flags=re.MULTILINE | re.DOTALL,
)
src = src.replace(
    '[NorbixRoute("/{version}/notifications/emails/campaigns/{campaignId}/messages/{id}", "GET")]',
    '[NorbixRoute("/{version}/notifications/emails/campaigns/{campaignId}/messages/{notificationId}", "GET")]',
)

match = re.search(rf"namespace\s+{re.escape(namespace)}\s*\{{", src)
if match:
    body = src[match.end():]
    end = body.rfind("}")
    src = body[:end] if end >= 0 else body

lines = src.splitlines()
filtered = []
i = 0
while i < len(lines):
    line = lines[i]
    if re.match(r"\s*public\s+partial\s+interface\s+I[A-Za-z0-9_]+", line):
        depth = 0
        saw_open = False
        while i < len(lines):
            depth += lines[i].count("{") - lines[i].count("}")
            saw_open = saw_open or "{" in lines[i]
            i += 1
            if saw_open and depth <= 0:
                break
        continue
    filtered.append(line)
    i += 1
src = "\n".join(filtered)

print(src.strip())
PY
}

clean "$TMP_API" "$TYPES_DIR/Api.dtos.cs" "Norbix.Sdk.Types.Api"
clean "$TMP_HUB" "$TYPES_DIR/Hub.dtos.cs" "Norbix.Sdk.Types.Hub"

echo "[sync-types] done. Run 'dotnet build' to regenerate SDK module classes via the source generator."
