#!/usr/bin/env python3
"""Regenerate src/Norbix.Sdk.Types/Generated/{Api,Hub}.dtos.cs from a running gateway.

    python3 scripts/sync-types.py --api http://localhost:5002 --hub http://localhost:5001

For each surface the script runs the `x csharp <url> <Api|Hub>` exporter (the
`x` dotnet tool, `dotnet tool install -g x`) into a temporary folder and then
rewrites the raw output into the shape this SDK ships:

* one flat file-scoped namespace (`Norbix.Sdk.Types.Api` / `.Hub`) instead of
  one block per gateway namespace; only `System.*` usings plus `Norbix.Sdk.Types`;
* `[Route(...)]` -> `[NorbixRoute(...)]`, `IReturn<T>` -> `INorbixRequest<T>`,
  `IReturnVoid` -> `INorbixRequest<object>` (the names of the upstream framework
  never appear in the public repo);
* `[Api(...)]`, `[ApiMember(...)]` and `[Ignore]` lines dropped (documentation /
  server-side attributes with no client meaning);
* the first declaration of a type wins when two gateway namespaces declare the
  same name (the SDK has one namespace);
* the auth markers `INorbixUnauthenticated` / `INorbixOptionalAuth` are copied
  from the file that is being replaced: the contract does not say which
  endpoint needs no credentials, the SDK does. A new endpoint that needs a
  marker is added to the existing file once, by hand, and kept from then on.

Two runs against the same gateway give byte-identical files, so a non-empty
`git diff` afterwards is a real contract change — read it before committing.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
GENERATED = REPO / "src" / "Norbix.Sdk.Types" / "Generated"

HEADER = """// <auto-generated>
//   Regenerated by internal contract workflow — do not edit by hand.
// </auto-generated>

#nullable enable annotations
#nullable disable warnings

#pragma warning disable CS0114, CS1570, CS0102, CS0108, CS0618
"""

MARKERS = ("INorbixUnauthenticated", "INorbixOptionalAuth")
TYPE_DECL = re.compile(r"^\s*public (?:partial )?(?:class|interface|enum|struct) ([A-Za-z0-9_]+)")
DROP_ATTR = re.compile(r"^\s*\[(Api|ApiMember|Ignore)\b.*\]\s*$")


def export(url: str, surface: str, out_dir: Path) -> str:
    subprocess.run(["x", "csharp", url, surface], cwd=out_dir, check=True, capture_output=True, text=True)
    return (out_dir / f"{surface}.dtos.cs").read_text(encoding="utf-8")


def existing_markers(path: Path) -> dict[str, list[str]]:
    """{type name: [markers]} read from the file that is about to be replaced."""
    found: dict[str, list[str]] = {}
    if not path.exists():
        return found
    lines = path.read_text(encoding="utf-8").splitlines()
    for i, line in enumerate(lines):
        m = TYPE_DECL.match(line)
        if not m:
            continue
        nxt = lines[i + 1] if i + 1 < len(lines) else ""
        if nxt.lstrip().startswith(":"):
            marks = [mk for mk in MARKERS if re.search(rf"\b{mk}\b", nxt)]
            if marks:
                found[m.group(1)] = marks
    return found


def transform(raw: str, surface: str, markers: dict[str, list[str]]) -> str:
    lines = raw.splitlines()

    # 1. drop the exporter's options block (/* Options: ... */)
    if lines and lines[0].startswith("/* Options:"):
        end = next(i for i, l in enumerate(lines) if l.strip() == "*/")
        lines = lines[end + 1 :]

    # 2. usings: keep System.*, drop the rest; namespaces: flatten
    body: list[str] = []
    uses_json_nodes = False
    for line in lines:
        if line.startswith("using "):
            continue
        if line.startswith("namespace "):
            continue
        if line == "{" or line == "}":
            continue  # namespace braces sit at column 0; type braces are indented
        body.append(line)

    # 3. framework names -> ours; server-only attributes dropped
    out: list[str] = []
    for line in body:
        if DROP_ATTR.match(line):
            continue
        line = line.replace("[Route(", "[NorbixRoute(")
        line = re.sub(r"\bIReturnVoid\b", "INorbixRequest<object>", line)
        line = re.sub(r"\bIReturn<", "INorbixRequest<", line)
        if "JsonObject" in line or "JsonNode" in line or "JsonArray" in line:
            uses_json_nodes = True
        out.append(line)

    # 4. one declaration per type name (first wins); the doc comment + attributes
    #    right above a dropped duplicate go with it
    deduped: list[str] = []
    seen: set[str] = set()
    i = 0
    while i < len(out):
        m = TYPE_DECL.match(out[i])
        if m and m.group(1) in seen:
            # remove the preamble (comments / attributes / blank) already emitted
            while deduped and (deduped[-1].strip() == "" or deduped[-1].lstrip().startswith(("///", "["))):
                deduped.pop()
            # skip to the type's closing brace at its indentation
            indent = len(out[i]) - len(out[i].lstrip())
            j = i + 1
            while j < len(out) and not (out[j].startswith(" " * indent + "}") and len(out[j]) - len(out[j].lstrip()) == indent):
                j += 1
            i = j + 1
            continue
        if m:
            seen.add(m.group(1))
        deduped.append(out[i])
        i += 1
    out = deduped

    # 5. auth markers carried over from the previous file
    marked: list[str] = []
    i = 0
    while i < len(out):
        line = out[i]
        marked.append(line)
        m = TYPE_DECL.match(line)
        if m and m.group(1) in markers and "enum " not in line:
            extra = [mk for mk in markers[m.group(1)]]
            nxt = out[i + 1] if i + 1 < len(out) else ""
            if nxt.lstrip().startswith(":"):
                for mk in extra:
                    if not re.search(rf"\b{mk}\b", nxt):
                        nxt = nxt + ", " + mk
                marked.append(nxt)
                i += 2
                continue
            marked.append("        : " + ", ".join(extra))
        i += 1
    out = marked

    # 6. trim leading / trailing blank lines, collapse runs of 3+ blank lines
    text = "\n".join(out)
    text = re.sub(r"\n{3,}", "\n\n", text).strip("\n")

    usings = ["System", "System.IO", "System.Collections"]
    if uses_json_nodes:
        usings.append("System.Text.Json.Nodes")
    usings += ["System.Collections.Generic", "System.Runtime.Serialization", "Norbix.Sdk.Types"]
    using_block = "\n".join(f"using {u};" for u in usings)
    return f"{HEADER}\n{using_block}\n\nnamespace Norbix.Sdk.Types.{surface};\n\n{text}\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--api", help="base URL of a running Api host (writes Api.dtos.cs)")
    ap.add_argument("--hub", help="base URL of a running Hub host (writes Hub.dtos.cs)")
    args = ap.parse_args()
    if not args.api and not args.hub:
        ap.error("give --api and/or --hub")

    with tempfile.TemporaryDirectory() as tmp:
        for surface, url in (("Api", args.api), ("Hub", args.hub)):
            if not url:
                continue
            target = GENERATED / f"{surface}.dtos.cs"
            raw = export(url, surface, Path(tmp))
            text = transform(raw, surface, existing_markers(target))
            target.write_text(text, encoding="utf-8")
            n_types = sum(1 for l in text.splitlines() if TYPE_DECL.match(l))
            n_routes = text.count("[NorbixRoute(")
            print(f"{target.relative_to(REPO)}: {n_types} types, {n_routes} routes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
