# Refresh src/Norbix.Sdk.Types/Generated/Api.dtos.cs and Hub.dtos.cs from the
# gateway /metadata endpoints. PowerShell mirror of sync-types.sh.

[CmdletBinding()]
param(
    [ValidateSet('local', 'prod')]
    [string]$Mode = 'local',
    [string]$ApiUrl,
    [string]$HubUrl
)

$ErrorActionPreference = 'Stop'
$root = Resolve-Path "$PSScriptRoot\.."
$typesDir = Join-Path $root 'src/Norbix.Sdk.Types/Generated'
New-Item -ItemType Directory -Force -Path $typesDir | Out-Null

if (-not $ApiUrl) {
    $ApiUrl = if ($Mode -eq 'prod') { 'https://api.norbix.dev' } else { 'http://localhost:5002' }
}
if (-not $HubUrl) {
    $HubUrl = if ($Mode -eq 'prod') { 'https://hub.norbix.dev' } else { 'http://localhost:5001' }
}

Write-Host "[sync-types] api-url: $ApiUrl"
Write-Host "[sync-types] hub-url: $HubUrl"

if (-not (Get-Command dotnet -ErrorAction SilentlyContinue)) {
    throw "[sync-types] dotnet SDK is required (https://aka.ms/dotnet)"
}

Push-Location $root
try {
    dotnet tool restore | Out-Host
}
catch {
    Write-Host "[sync-types] dotnet tool restore failed; will try global x or /types/csharp"
}
finally {
    Pop-Location
}

function Add-GlobalNamespace([string]$url, [string]$ns) {
    $separator = if ($url.Contains('?')) { '&' } else { '?' }
    return "$url${separator}GlobalNamespace=$ns"
}

function Invoke-X([string]$url, [string]$out, [string]$ns) {
    $typedUrl = Add-GlobalNamespace $url $ns
    Write-Host "[sync-types]   csharp $typedUrl -> $out"

    Push-Location $root
    try {
        dotnet x csharp $typedUrl $out | Out-Host
    }
    catch {
    }
    finally {
        Pop-Location
    }
    if ((Test-Path $out) -and ((Get-Item $out).Length -gt 0)) {
        return
    }

    if (Get-Command x -ErrorAction SilentlyContinue) {
        try {
            x csharp $typedUrl $out | Out-Host
        }
        catch {
        }
        if ((Test-Path $out) -and ((Get-Item $out).Length -gt 0)) {
            return
        }
    }

    $directUrl = "$($url.TrimEnd('/'))/types/csharp?GlobalNamespace=$ns"
    Write-Host "[sync-types]   falling back to $directUrl"
    Invoke-WebRequest -Uri $directUrl -OutFile $out
}

$tmpApi = [System.IO.Path]::GetTempFileName() + '.cs'
$tmpHub = [System.IO.Path]::GetTempFileName() + '.cs'
try {
    Invoke-X $ApiUrl $tmpApi 'Norbix.Sdk.Types.Api'
    Invoke-X $HubUrl $tmpHub 'Norbix.Sdk.Types.Hub'

    function Clean-File([string]$inputPath, [string]$outputPath, [string]$ns) {
        $header = @(
            '// <auto-generated>',
            '//   Regenerated by scripts/sync-types.ps1 — do not edit by hand.',
            '// </auto-generated>',
            '',
            '#nullable enable annotations',
            '#nullable disable warnings',
            '',
            'using System;',
            'using System.Collections.Generic;',
            'using System.Runtime.Serialization;',
            'using Norbix.Sdk.Types;',
            '',
            "namespace $ns;",
            ''
        )
        $body = Get-Content $inputPath -Raw
        $body = $body -replace '(?m)^using ServiceStack\b.*\r?\n', ''
        $body = $body -replace '(?m)^using ServiceStack\..*\r?\n', ''
        $body = $body -replace '(?m)^using System\b.*\r?\n', ''
        $body = $body -replace '(?m)^using System\..*\r?\n', ''
        $body = $body -replace "(?m)^using $([regex]::Escape($ns));\s*\r?\n", ''
        $body = $body -replace '(?m)^\s*\[Api[^\]]*\]\s*\r?\n', ''
        $body = $body -replace '(?m)^\s*\[Ignore\]\s*\r?\n', ''
        $body = $body -replace 'IReturn<([^>]+)>', 'INorbixRequest<$1>'
        $body = $body -replace '\bIReturnVoid\b', 'INorbixRequest'
        $body = $body -replace '\[Route\(', '[NorbixRoute('
        $body = $body -replace '\bRoute\(', 'NorbixRoute('
        $body = $body -replace '\bIPost\b|\bIGet\b|\bIHasSessionId\b|\bIHasBearerToken\b', ''
        $body = [regex]::Replace(
            $body,
            '(public\s+partial\s+class\s+[A-Za-z0-9_]+(?:<[^>]+>)?)\s*(?::\s*([^{]+))?\s*\{',
            {
                param($m)
                $name = $m.Groups[1].Value
                $bases = $m.Groups[2].Value
                if ([string]::IsNullOrWhiteSpace($bases)) {
                    return "$name`n    {"
                }
                $kept = @(
                    $bases.Split(',') |
                        ForEach-Object { $_.Trim() } |
                        Where-Object { $_ -and ((-not $_.StartsWith('I')) -or $_.StartsWith('INorbixRequest')) }
                )
                if ($kept.Count -eq 0) {
                    return "$name`n    {"
                }
                return "$name`n        : $($kept -join ', ')`n    {"
            },
            [System.Text.RegularExpressions.RegexOptions]::Multiline)
        $body = [regex]::Replace(
            $body,
            '(public\s+partial\s+class\s+(?:MarketplaceIntegration|WebhookIntegration)\s*:\s*Integration\s*\{(?:(?!^\s*\}).)*?)public\s+virtual\s+string\s+Capability\s*\{\s*get;\s*set;\s*\}',
            '$1public override string Capability { get; set; }',
            [System.Text.RegularExpressions.RegexOptions]::Multiline -bor [System.Text.RegularExpressions.RegexOptions]::Singleline)
        $body = $body -replace '\bIList<JSchema>', 'JSchema[]'
        $body = $body -replace '\bIList<JToken>', 'JToken[]'
        $body = $body -replace '\bIList<string>', 'string[]'
        $body = $body -replace '\bDictionary<([^,<>\s]+)<([^<>]+)>>', 'Dictionary<$1, $2>'
        $body = $body -replace '\bNameValueCollection\b|\bFileInfo\b|\bFunc<IDisposable>\b|\bCookie\b|\bHttpStatusCode\b', 'object'
        $body = [regex]::Replace(
            $body,
            '(public\s+partial\s+class\s+UpdateDatabaseSchemaSettingsRequest\s*\r?\n\s*:\s*CodeMashRequestBase,\s*INorbixRequest<EmptyResponse>\s*\r?\n\s*\{(?:(?!^\s*\}).)*?^\s*\})',
            {
                param($m)
                $block = $m.Groups[1].Value
                if ($block -match 'public\s+virtual\s+string\s+Id\s*\{\s*get;\s*set;\s*\}') {
                    return $block
                }
                $open = $block.IndexOf('{')
                return $block.Substring(0, $open + 1) + "`n`n        public virtual string Id { get; set; }" + $block.Substring($open + 1)
            },
            [System.Text.RegularExpressions.RegexOptions]::Multiline -bor [System.Text.RegularExpressions.RegexOptions]::Singleline,
            [TimeSpan]::FromSeconds(1))
        $body = [regex]::Replace(
            $body,
            '(public\s+partial\s+class\s+DeleteEmailCampaignRequest\s*\r?\n\s*:\s*CodeMashRequestBase,\s*INorbixRequest<EmptyResponse>\s*\r?\n\s*\{(?:(?!^\s*\}).)*?^\s*\})',
            {
                param($m)
                $block = $m.Groups[1].Value
                $members = [System.Collections.Generic.List[string]]::new()
                if ($block -notmatch 'public\s+virtual\s+string\s+Id\s*\{\s*get;\s*set;\s*\}') {
                    $members.Add('        public virtual string Id { get; set; }')
                }
                if ($block -notmatch 'public\s+virtual\s+string\s+DatabaseIntegrationId\s*\{\s*get;\s*set;\s*\}') {
                    $members.Add('        public virtual string DatabaseIntegrationId { get; set; }')
                }
                if ($members.Count -eq 0) {
                    return $block
                }
                $open = $block.IndexOf('{')
                return $block.Substring(0, $open + 1) + "`n" + ($members -join "`n") + $block.Substring($open + 1)
            },
            [System.Text.RegularExpressions.RegexOptions]::Multiline -bor [System.Text.RegularExpressions.RegexOptions]::Singleline,
            [TimeSpan]::FromSeconds(1))
        $body = $body.Replace(
            '[NorbixRoute("/{version}/notifications/emails/campaigns/{campaignId}/messages/{id}", "GET")]',
            '[NorbixRoute("/{version}/notifications/emails/campaigns/{campaignId}/messages/{notificationId}", "GET")]')

        $match = [regex]::Match($body, "namespace\s+$([regex]::Escape($ns))\s*\{")
        if ($match.Success) {
            $body = $body.Substring($match.Index + $match.Length)
            $lastBrace = $body.LastIndexOf('}')
            if ($lastBrace -ge 0) {
                $body = $body.Substring(0, $lastBrace)
            }
        }

        $lines = $body -split "\r?\n"
        $filtered = [System.Collections.Generic.List[string]]::new()
        for ($i = 0; $i -lt $lines.Length; $i++) {
            if ($lines[$i] -match '^\s*public\s+partial\s+interface\s+I[A-Za-z0-9_]+') {
                $depth = 0
                $sawOpen = $false
                while ($i -lt $lines.Length) {
                    $depth += ([regex]::Matches($lines[$i], '\{')).Count
                    $depth -= ([regex]::Matches($lines[$i], '\}')).Count
                    if ($lines[$i].Contains('{')) { $sawOpen = $true }
                    if ($sawOpen -and $depth -le 0) { break }
                    $i++
                }
                continue
            }
            $filtered.Add($lines[$i])
        }
        $body = $filtered -join "`n"

        ($header -join "`n") + "`n" + $body | Set-Content -NoNewline -Path $outputPath -Encoding utf8
    }

    Clean-File $tmpApi (Join-Path $typesDir 'Api.dtos.cs') 'Norbix.Sdk.Types.Api'
    Clean-File $tmpHub (Join-Path $typesDir 'Hub.dtos.cs') 'Norbix.Sdk.Types.Hub'

    Write-Host "[sync-types] done. Run 'dotnet build' to regenerate SDK module classes via the source generator."
}
finally {
    Remove-Item -Force $tmpApi -ErrorAction SilentlyContinue
    Remove-Item -Force $tmpHub -ErrorAction SilentlyContinue
}
